apiVersion: apps/v1
kind: Deployment
metadata:
  name: himarket-server
  labels:
    app: himarket-server
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app: himarket-server
  template:
    metadata:
      labels:
        app: himarket-server
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "himarket.serviceAccountName" . }}
      {{- if .Values.mysql.enabled }}
      # 等待 MySQL 就绪后再启动应用
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.35  # 轻量级镜像
          command: ['sh', '-c']
          args:
            - |
              echo "等待 MySQL 就绪..."
              until nc -z mysql-headless-svc 3306; do
                echo "MySQL 未就绪，等待 5 秒..."
                sleep 5
              done
              echo "MySQL 已就绪！"
      {{- end }}
      containers:
        - name: server
          image: "{{ .Values.hub }}/{{ .Values.server.image.repository }}:{{ .Values.server.image.tag}}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.server.serverPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: himarket-server        # 非敏感配置
            - secretRef:
                name: himarket-server-secret # 敏感配置（包括数据库连接）
{{/*          {{- with .Values.livenessProbe }}*/}}
{{/*          livenessProbe:*/}}
{{/*            {{- toYaml . | nindent 12 }}*/}}
{{/*          {{- end }}*/}}
{{/*          {{- with .Values.readinessProbe }}*/}}
{{/*          readinessProbe:*/}}
{{/*            {{- toYaml . | nindent 12 }}*/}}
{{/*          {{- end }}*/}}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
