spring:
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/${db.name}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



db:
  host: rm-uf6pc9n1jzi2478l4eo.mysql.rds.aliyuncs.com
  port: 3306
  name: Portal_DB
  username: portal_test
  password: portal-Go

jwt:
  secret: 4GsGNFwqzqMk3CFZqcq9IjJWrTtv+fYNbB4Baexg67A=
  expiration: 2h

logging:
  level:
    org.springframework.security: DEBUG
    # org.springframework.web: DEBUG
    # org.springframework.boot: DEBUG
    # org.springframework: INFO

#nacos:
#  console:
#    api:
#      base-url: "http://118.178.188.80:30080" # 替换为实际地址
#      access-token: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTc1MjU4Mzg4NX0.v9cubow7kmMBFYmA9MhLjfSg4bAqXXm720Fiqkg1DFI" # 替换为实际Token

nacos:
  maintainer:
    server-addr: "http://8.136.107.184:8848"
    username: "nacos"
    password: "zhangxiaodan"