spring:
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/${db.name}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

db:
  host: rm-bp1kp86mbm7009g7heo.mysql.rds.aliyuncs.com
  port: 3306
  name: api_open_platform
  username: YourDBName
  password: YourDBPassword
#  username: root
#  password: 12345678